
module.exports = [
	
	require('../macros/expression'),
	require('../macros/number'),
	require('../macros/string'),
	require('../macros/name'),
	require('../macros/symbol'),
	require('../macros/set'),
	require('../macros/set_local'),
	require('../macros/get'),
	require('../macros/dollarize'),
	require('../macros/callable'),
	require('../macros/string-symbol'),
	require('../macros/import'),
	require('../macros/export'),
	require('../macros/typeof'),
	require('../macros/ref'),
	require('../macros/func'),
	require('../macros/function'),
	require('../macros/accepts'),
	require('../macros/repeat'),
	require('../macros/break'),
	require('../macros/if'),
	require('../macros/else'),
	require('../macros/true'),
	require('../macros/false'),
	require('../macros/plus'),
	require('../macros/minus'),
	require('../macros/equals'),
	require('../macros/greater'),
	require('../macros/less'),
	require('../macros/not'),
	require('../macros/and'),
	require('../macros/or'),
	require('../macros/xor'),
	require('../macros/omit')
]
